version: "3.1"

services:
  db:
    image: mysql:8-oracle
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=test
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
    environment:
      - ADMINER_DESIGN=pepa-linha
